name: Release Alfred Workflow

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"

env:
  WORKFLOW_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Build .alfredworkflow
        run: |
          name="${{ env.WORKFLOW_NAME }}"
          zip --quiet --recurse-paths "$name.alfredworkflow" . --exclude ".git*"

      - name: Upload .alfredworkflow file
        id: upload-alfredworkflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.WORKFLOW_NAME }}.alfredworkflow
          asset_name: ${{ env.WORKFLOW_NAME }}.alfredworkflow
          asset_content_type: application/zip
